version: "3"
services:
  react:
    build:
      context: .
      dockerfile: ./dockerfile/react/Dockerfile
    container_name: no_more_ramen_container_react
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/frontend
    command: sh -c "cd frontend && yarn install && yarn start"
    ports:
      - "3000:3000"
